Reworked config file access logic

diff --git a/bin/start_consul_agent b/bin/start_consul_agent
--- a/bin/start_consul_agent
+++ b/bin/start_consul_agent
@@ -21,14 +21,14 @@ USER=$(id -u)
 GROUP=$(id -g)
 logd "Running as $USER:$GROUP"
 
-if [ -e /etc/consul/consul.json ] && { [ ! -r /etc/consul/consul.json ] || [ ! -w /etc/consul/consul.json ]; }; then
-	loge "[ERR] Can't access Consul configuration file! (/etc/consul/consul.json)"
-	exit 1
-fi
-
 if [ -e ${TEMPLATE_DIR:=/etc/consul}/consul.json.template ]; then
 	cp ${TEMPLATE_DIR}/consul.json.template /etc/consul/consul.json
 	chmod 660 /etc/consul/consul.json
+fi
+
+if [ ! -r /etc/consul/consul.json ] || [ ! -w /etc/consul/consul.json ]; then
+	loge "[ERR] Can't access Consul configuration file! (/etc/consul/consul.json)"
+	exit 1
 fi
 
 # Add the Consul CA to the trusted list
