* Remove the .sh extension on the startup script

diff --git a/bin/start_consul b/bin/start_consul
--- a/bin/start_consul
+++ b/bin/start_consul
@@ -1,12 +1,12 @@
 #!/bin/ash
-
+SCRIPT_NAME=$(basename -- "$0")
 log() {
-	printf '%s\n' "$@"|awk '{print strftime("%FT%T%z",systime()),"[INFO] start_consul.sh:",$0}'
+    printf "[INFO] ${SCRIPT_NAME}: %s\n" "$@"
 }
 logd() {
-	if [ ${DEBUG:-} ]; then
-		printf '%s\n' "$@"|awk '{print strftime("%FT%T%z",systime()),"[DEBUG] start_consul.sh:",$0}'
-	fi
+    if [ ${DEBUG:-} ]; then
+        printf "[DEBUG] ${SCRIPT_NAME}: %s\n" "$@"
+    fi
 }
 
 set_consul_performance() {
@@ -77,9 +77,14 @@ if [ -e "/data/raft/raft.db" ]; then # This is a restart
 #	consul validate -quiet /etc/consul/consul.json || exit 1
 	logd 'Starting Consul'
 	unset CONSUL_ENCRYPT_TOKEN
+	unset CONSUL_BOOTSTRAP_HOST
+	unset CONSUL_CLUSTER_SIZE
 
-	exec -a consul su-exec consul:consul consul agent -config-dir=/etc/consul/ -data-dir=/data -datacenter="$CONSUL_DC_NAME" -domain="${CONSUL_DOMAIN:=consul}" -retry-join="$CONSUL_DNS_NAME" -rejoin
-else
+	exec -a consul su-exec consul:consul consul agent -server -ui -config-dir=/etc/consul/ -data-dir=/data -datacenter="$CONSUL_DC_NAME" -domain="${CONSUL_DOMAIN:=consul}" -retry-join="$CONSUL_DNS_NAME" -rejoin
+
+else # This is the first start
+	if [ "$CONSUL_DC_NAME" ] && [ "$CONSUL_ENCRYPT_TOKEN" ] && [ "$CONSUL_CLUSTER_SIZE" ] && [ "$CONSUL_DNS_NAME" ]; then
+		logd 'Starting Consul for the first time, using CONSUL_DC_NAME & BOOTSTRAP_HOST environment variables'
 		# Create Consul's data directory
 		mkdir -p -m 775 /data
 		chown -R consul: /data
@@ -91,8 +96,22 @@ else
 		fi
 		su -s /bin/sh consul -c "{ rm /etc/consul/consul.json; jq '.acl_datacenter = env.CONSUL_ACL_DC' > /etc/consul/consul.json; } < /etc/consul/consul.json"
 
-		exec -a consul su-exec consul:consul consul agent -config-dir=/etc/consul/ -data-dir=/data -datacenter="$CONSUL_DC_NAME" -domain="${CONSUL_DOMAIN:=consul}" -retry-join=consul -retry-join="${CONSUL_BOOTSTRAP_HOST:-127.0.0.1}" -retry-join="$CONSUL_DNS_NAME" -encrypt="$CONSUL_ENCRYPT_TOKEN"
+	# Log Consul bootstrap host to the console
+		if [ "${CONSUL_BOOTSTRAP_HOST:-127.0.0.1}" = 127.0.0.1 ]; then
+			logd "Bootstrap host is $(hostname -s)"
+			logd "Please remember to bootstrap the ACL system by running: curl --cert client_certificate.pem --key client_certificate.key --cacert ca.pem -XPUT 'https://${CONSUL_DNS_NAME:-consul.service.consul}:$(jq '.ports.https' /etc/consul/consul.json)/v1/acl/bootstrap'"
+		else
+			logd "Bootstrap host is ${CONSUL_BOOTSTRAP_HOST}"
+		fi
+
+# Bug in 1.0.6 fails if the key data_dir is not included
+#		consul validate /etc/consul/consul.json || exit 1
+		exec -a consul su-exec consul:consul consul agent -server -ui -config-dir=/etc/consul/ -data-dir=/data -datacenter="$CONSUL_DC_NAME" -domain="${CONSUL_DOMAIN:=consul}" -bootstrap-expect="$CONSUL_CLUSTER_SIZE" -retry-join=consul -retry-join="${CONSUL_BOOTSTRAP_HOST:-127.0.0.1}" -retry-join="$CONSUL_DNS_NAME" -encrypt="$CONSUL_ENCRYPT_TOKEN"
 	else
+		printf 'Consul agent configuration\nUsage\n-----\n' >&2
+		printf 'You must always set the following environment variables to run this container:\nCONSUL_DC_NAME: The desired name for your Consul datacenter\n\n' >&2
+		printf 'The following environment variables are mandatory only on the first run of the container:\nCONSUL_ENCRYPT_TOKEN: RPC encryption token, can be generated by running consul keygen\nCONSUL_CLUSTER_SIZE: The expected number of server nodes in your cluster\nCONSUL_DNS_NAME: The DNS name for your cluster (eg: consul.service.consul)\n\n' >&2
+		printf 'The following environment variables are used to configure the cluster (if provided):\nCONSUL_ACL_DC: The Consul ACL Datacenter, defaults to the value of CONSUL_DC_NAME if not provided\nCONSUL_BOOTSTRAP_HOST: A Consul server node to join on startup, only used the first time the container runs. Defaults to 127.0.0.1\nCONSUL_ENVIRONMENT: if set to "prod", it will configure Consul for high performance. If it is not set and you are running on AWS EC2, Google Cloud Engine (GCE) ot Azure, a performance setting will be set according to your instance type\n\n' >&2
 		exit 1
 	fi
 fi
