Add loge function

diff --git a/bin/start_consul b/bin/start_consul
--- a/bin/start_consul
+++ b/bin/start_consul
@@ -3,6 +3,9 @@ SCRIPT_NAME=$(basename -- "$0")
 log() {
     printf "[INFO] ${SCRIPT_NAME}: %s\n" "$@"
 }
+loge() {
+    printf "[ERR] ${SCRIPT_NAME}: %s\n" "$@" >&2
+}
 logd() {
     if [ ${DEBUG:-} ]; then
         printf "[DEBUG] ${SCRIPT_NAME}: %s\n" "$@"
@@ -19,7 +22,7 @@ GROUP=$(id -g)
 logd "Running as $USER:$GROUP"
 
 if [ -e /etc/consul/consul.json ] && { [ ! -r /etc/consul/consul.json ] || [ ! -w /etc/consul/consul.json ]; }; then
-	printf "[ERR] Can't access Consul configuration file! (/etc/consul/consul.json)\n" >&2
+	loge "[ERR] Can't access Consul configuration file! (/etc/consul/consul.json)"
 	exit 1
 fi
 
@@ -118,10 +121,10 @@ else # This is the first start
 
 		exec -a consul consul agent -server -ui -config-dir=/etc/consul/ -data-dir=/data -datacenter="$CONSUL_DC_NAME" -domain="${CONSUL_DOMAIN:=consul}" -bootstrap-expect="$CONSUL_CLUSTER_SIZE" -retry-join=consul -retry-join="${CONSUL_BOOTSTRAP_HOST:-127.0.0.1}" -retry-join="$CONSUL_DNS_NAME" -encrypt="$CONSUL_ENCRYPT_TOKEN"
 	else
-		printf 'Consul agent configuration\nUsage\n-----\n' >&2
-		printf 'You must always set the following environment variables to run this container:\nCONSUL_DC_NAME: The desired name for your Consul datacenter\n\n' >&2
-		printf 'The following environment variables are mandatory only on the first run of the container:\nCONSUL_ENCRYPT_TOKEN: RPC encryption token, can be generated by running consul keygen\nCONSUL_CLUSTER_SIZE: The expected number of server nodes in your cluster\nCONSUL_DNS_NAME: The DNS name for your cluster (eg: consul.service.consul)\n\n' >&2
-		printf 'The following environment variables are used to configure the cluster (if provided):\nCONSUL_ACL_DC: The Consul ACL Datacenter, defaults to the value of CONSUL_DC_NAME if not provided\nCONSUL_BOOTSTRAP_HOST: A Consul server node to join on startup, only used the first time the container runs. Defaults to 127.0.0.1\nCONSUL_ENVIRONMENT: if set to "prod", it will configure Consul for high performance. If it is not set and you are running on AWS EC2, Google Cloud Engine (GCE) ot Azure, a performance setting will be set according to your instance type\n\n' >&2
+		loge 'Consul agent configuration\nUsage\n-----'
+		loge 'You must always set the following environment variables to run this container:\nCONSUL_DC_NAME: The desired name for your Consul datacenter\n'
+		loge 'The following environment variables are mandatory only on the first run of the container:\nCONSUL_ENCRYPT_TOKEN: RPC encryption token, can be generated by running consul keygen\nCONSUL_CLUSTER_SIZE: The expected number of server nodes in your cluster\nCONSUL_DNS_NAME: The DNS name for your cluster (eg: consul.service.consul)\n'
+		loge 'The following environment variables are used to configure the cluster (if provided):\nCONSUL_ACL_DC: The Consul ACL Datacenter, defaults to the value of CONSUL_DC_NAME if not provided\nCONSUL_BOOTSTRAP_HOST: A Consul server node to join on startup, only used the first time the container runs. Defaults to 127.0.0.1\nCONSUL_ENVIRONMENT: if set to "prod", it will configure Consul for high performance. If it is not set and you are running on AWS EC2, Google Cloud Engine (GCE) ot Azure, a performance setting will be set according to your instance type\n'
 		exit 1
 	fi
 fi
diff --git a/bin/start_consul_agent b/bin/start_consul_agent
--- a/bin/start_consul_agent
+++ b/bin/start_consul_agent
@@ -3,6 +3,9 @@ SCRIPT_NAME=$(basename -- "$0")
 log() {
     printf "[INFO] ${SCRIPT_NAME}: %s\n" "$@"
 }
+loge() {
+    printf "[ERR] ${SCRIPT_NAME}: %s\n" "$@" >&2
+}
 logd() {
     if [ ${DEBUG:-} ]; then
         printf "[DEBUG] ${SCRIPT_NAME}: %s\n" "$@"
@@ -19,7 +22,7 @@ GROUP=$(id -g)
 logd "Running as $USER:$GROUP"
 
 if [ -e /etc/consul/consul.json ] && { [ ! -r /etc/consul/consul.json ] || [ ! -w /etc/consul/consul.json ]; }; then
-	printf "[ERR] Can't access Consul configuration file! (/etc/consul/consul.json)\n" >&2
+	loge "[ERR] Can't access Consul configuration file! (/etc/consul/consul.json)"
 	exit 1
 fi
 
